language: ruby
env:
  - DB=postgres
rvm:
  - 1.9.3
bundler_args: --without development
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:setup
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  email:
    recipients:
      - craig@enspiral.com
  hipchat: 3d318fc3e1f401238a50171784b534@Craftworks General